// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kofionrbrtcwmmevbtxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZmlvbnJicnRjd21tZXZidHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODMxNDEsImV4cCI6MjA1Mjk1OTE0MX0.fn8SS0Ne2wR5CgwABM-SHWAtC6bjfONntb0GjnGJM8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);